/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface components {
  /** An order for a pets from the pet store */
  Order: {
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: string;
    /** Order Status */
    status?: "placed" | "approved" | "delivered";
    complete?: boolean;
  };
  /** A category for a pet */
  Category: {
    id?: number;
    name?: string;
  };
  /** A User who is purchasing from the pet store */
  User: {
    id?: number;
    username?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    /** User Status */
    userStatus?: number;
  };
  /** A tag for a pet */
  Tag: {
    id?: number;
    name?: string;
  };
  /** A pet for sale in the pet store */
  Pet: {
    id?: number;
    category?: components["Category"];
    name: string;
    photoUrls: string[];
    tags?: components["Tag"][];
    /** pet status in the store */
    status?: "available" | "pending" | "sold";
  };
  /** Describes the result of uploading an image resource */
  ApiResponse: {
    code?: number;
    type?: string;
    message?: string;
  };

  requestBodies: {
    /** List of user object */
    UserArray: { [key: string]: any };
    /** Pet object that needs to be added to the store */
    Pet: { [key: string]: any };
  };
}

export interface operations {}
